services:
  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"  # Blob Storage
    environment:
      - AZURITE_ACCOUNTS=myaccount=mykey
    volumes:
      - azurite-data:/data
    command: azurite --blobPort 10000

volumes:
  pgdata:
  azurite-data: